[package]
name = "woff2"
version = "0.3.0"
authors = ["Brian Hanechak <brianh@cimpress.com>", "Emily Crandall Fleischman <emily.fleischman@cimpress.com>"]
edition = "2021"
license = "Apache-2.0"
keywords = ["woff2", "font", "parse"]
description = "WOFF2 decompression library"
repository = "https://github.com/Cimpress-MCP/woff2-rs"
readme = "readme.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = { version = "1.7.1", default-features = false }
four-cc = { version = "0.4.0", default-features = false }
safer-bytes = "0.2.0"
thiserror = "1.0.30"
bitvec = "1.0.0"
brotli = { version = "6.0.0", default-features = false }
alloc-no-stdlib = "2.0.4"

[dev-dependencies]
clap = { version = "4.5.13", features = ["derive"] }
ttf-parser = "0.24.0"

[features]
default = ["std"]
std = ["brotli/std", "bytes/std", "four-cc/std"]
